name: Deploy FRONTEND APP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FRONTEND_IMAGE: abisgit/firma-landing
  DOCKER_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Frontend Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.FRONTEND_IMAGE }}:${{ env.DOCKER_TAG }}
            ${{ env.FRONTEND_IMAGE }}:latest
          no-cache: true
          pull: true

      - name: Deploy Frontend via SSH
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.FRONTEND_SERVER_IP }}
          username: ubuntu
          key: ${{ secrets.FRONTEND_SERVER_SSH_KEY }}
          port: 22
          script: |
            set -euo pipefail

            # ---------- CONFIG ----------
            APP_NAME=ptgr-io
            BASE_DIR=frontends
            APP_DIR=${BASE_DIR}/${APP_NAME}
            LAST_TAG_FILE=${APP_DIR}/.last_deployed

            IMAGE=${{ env.FRONTEND_IMAGE }}
            NEW_TAG=${{ env.DOCKER_TAG }}

            echo "Deploying ${APP_NAME} → ${IMAGE}:${NEW_TAG}"

            mkdir -p "${APP_DIR}"
            cd "${APP_DIR}"

            # Pull image first
            sudo docker pull "${IMAGE}:${NEW_TAG}"

            # Read last tag
            LAST_TAG=""
            if [ -f "${LAST_TAG_FILE}" ]; then
              LAST_TAG=$(cat "${LAST_TAG_FILE}" || true)
            fi
            echo "Last deployed tag: ${LAST_TAG:-none}"

            # Stop & remove frontend container only
            sudo docker compose stop ${APP_NAME} || true
            sudo docker compose rm -f ${APP_NAME} || true

            # Cleanup old images (safe)
            sudo docker image prune -af || true

            # Export vars for docker-compose
            export FRONTEND_IMAGE="${IMAGE}"
            export DOCKER_TAG="${NEW_TAG}"

            # Start frontend
            sudo docker compose up -d --no-deps ${APP_NAME}

            # ---------- HEALTH CHECK ----------
            echo "Checking frontend availability..."
            SUCCESS=false
            for i in 1 2 3 4 5; do
              if curl -f -s http://localhost > /dev/null; then
                SUCCESS=true
                echo "Frontend is UP"
                break
              fi
              sleep 3
            done

            # ---------- ROLLBACK ----------
            if [ "${SUCCESS}" != "true" ]; then
              echo "Frontend health failed — rollback"

              if [ -n "${LAST_TAG}" ]; then
                sudo docker pull "${IMAGE}:${LAST_TAG}" || true
                export DOCKER_TAG="${LAST_TAG}"
                sudo docker compose up -d --no-deps ${APP_NAME}
              else
                echo "No previous tag found"
                exit 1
              fi
            fi

            echo "${NEW_TAG}" > "${LAST_TAG_FILE}"
            echo "Frontend deployed successfully"

            # Reload nginx proxy only
            sudo docker compose restart nginx || true

            sudo docker compose ps
            sudo docker compose logs ${APP_NAME} --tail 20